[build]
  command = "npm run build"
  node_bundler = "esbuild"
  publish = "dist/"

[dev]
  functionsPort = 1234

[functions]
  directory = "src/functions"

[functions.image]
  external_node_modules = ["chrome-aws-lambda"]
