export const $query = (selector: string) => document.querySelector(selector)
export const $queryAll = (selector: string) => document.querySelectorAll(selector)
export const $id = (id: string) => document.getElementById(id)
export const $className = (cls: string) => document.getElementsByClassName(cls)
export const $byName = (name: string) => document.getElementsByName(name)
export const $byTagName = (tagName: string) => document.getElementsByTagName(tagName)
export const $create = (tagName: string, attrs = {}) => Object.assign(document.createElement(tagName), attrs)
export const $append = (children: HTMLElement | Array<HTMLElement>, father = document.body) => Array.isArray(children)
  ? children.map(ch => father.appendChild(ch))
  : father.appendChild(children)
