name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3
        
      - name: Install Deno
        uses: maximousblk/setup-deno@v2.0.0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0

      - name: Instalar las dependencias
        run: pnpm i

      - name: Construir Astro
        run: pnpm run build

      - name: Subir a Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: cuando-juega-edlp
          entrypoint: server/entry.mjs
          root: dist
